### ISSUE TITLE
Crash in IOS while trying to register

### ISSUE THREAD

**Issue by adarshdev** [nventive/Binding.Salesforce.MarketingCloud#10]
![image](https://user-images.githubusercontent.com/18255638/69496035-a8335680-0ef3-11ea-952a-d8c8d46199ec.png)

**Comment by adarshdev** [comment]
While building the library we must add the bundle from static library as resource directory solves the issue.

**Comment by isc30** [comment]
Hi there, do you mind pointing me to the commit fixing this issue please?
I'm having a very similar issue

**Comment by adarshdev** [comment]
i dont think issue is fixed in the project here. What i did was creating a new binding solution from  the ios static library provided by marketing cloud
